
name: Update Chess Rating Chart

on:
  schedule:
    - cron: "0 12 * * *"  # Executa diariamente ao meio-dia (UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure ratings.json exists
        run: |
          if [ ! -f scripts/ratings.json ]; then
            echo '{"history": []}' > scripts/ratings.json
          fi

      - name: Fetch latest rating → update ratings.json
        run: |
          python scripts/fetch_ratings.py

      - name: Generate ASCII chart and update README
        run: |
          CHART=$(python scripts/plot_ascii.py)

          # Injeta o chart entre os marcadores
          UPDATED=$(awk -v chart="$CHART" '
            BEGIN { RS="<!-- CHESS_CHART_START -->|<!-- CHESS_CHART_END -->"; ORS=""; i=0 }
            { if (++i==1) printf "%s<!-- CHESS_CHART_START -->\n%s\n<!-- CHESS_CHART_END -->", $0, chart;
              else printf "%s", $0 }
          ' README.md)

          echo "$UPDATED" > README.md

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scripts/ratings.json README.md
          git commit -m "📊 Auto-update rating chart and data [skip ci]" || echo "Nothing to commit"
          git push
