name: Atualizar Chess.com Rating

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:  # Para rodar manualmente

jobs:
  update-rating:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Instalar dependências
      run: pip install requests

    - name: Rodar script para atualizar o gráfico
      run: python update_chess.py

    - name: Commit e push se houver alterações no README
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Atualizar gráfico de rating"
        git push
